"""
Django settings for myProject project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import django
from django.utils.encoding import force_str
django.utils.encoding.force_text = force_str

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
# 媒体储存根路径
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


# 认证用的model
AUTH_USER_MODEL = "myApp.User"  # 应用名.表名

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",  # 数据库引擎
        "NAME": "acgsite",  # 数据库名，先前创建的
        "USER": "root",  # 用户名，可以自己创建用户
        "PASSWORD": "root",  # 密码
        "HOST": "db",  # mysql服务所在的主机ip
        "PORT": "3306",  # mysql服务端口
        "OPTIONS": {"charset": "utf8mb4"},  # 编码集 一定要用utf8mb4！！！！
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1uya869km$m%mcffkbqbb5ml^q*ny1(k($o=o0(o+0920e+gh3"

# 生产环境请关闭
DEBUG = True

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myApp",
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "PAGE_SIZE": 5,
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myProject.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_TITLE = "管理后台"
SIMPLEUI_ANALYSIS = False
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单
    "system_keep": False,
    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    "menus": [
        {
            "app": "myApp",
            "name": "权限认证",
            "icon": "fas fa-user-shield",
            "models": [
                {"name": "用户数据", "icon": "fa fa-user", "url": "/admin/myApp/user/"},
                {"name": "用户组", "url": "/admin/auth/group/"},
                {
                    "name": "认证令牌",
                    "icon": "fas fa-user-shield",
                    "url": "/admin/authtoken/tokenproxy/",
                },
            ],
        },
        {
            "name": "数据管理",
            "models": [
                {
                    "name": "文章",
                    "url": "/admin/myApp/article/",
                },
                {
                    "name": "留言",
                    "url": "/admin/myApp/message/",
                },
                {
                    "name": "视频",
                    "url": "/admin/myApp/video/",
                },
            ],
        },
    ],
}
# Google Nm$l
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"
# 增加跨域忽略,去除Chrome的samesite限制
ALLOWED_HOSTS = ["*"]
#首页图标
CORS_ORIGIN_WHITELIST = (
    '*',
)
CORS_ALLOW_CREDENTIALS = True  # 指明在跨域访问中，后端是否支持对cookie的操作。

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    "VIEW",
)
CORS_ALLOW_HEADERS = (
    "XMLHttpRequest",
    "X_FILENAME",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "Pragma",
)