version: "3"
services:
  db:
    image: mysql:8.0
    # windows表迁移到linux上可能有大小写问题，这里设置忽略大小写
    command: --lower_case_table_names=1
    volumes:
      # - ./mysql:/var/lib/mysql
      - database-volume:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acgsite
    networks:
      - db_network
  django:
    restart: always
    build: ./backend
    command: bash wait-for.sh db:3306 -- bash -c "python3 manage.py migrate && python3 manage.py collectstatic --no-input &&  uwsgi uwsgi.ini"
    volumes:
      # - ./backend/myProject:/django
      - static-volume:/django/static
      - media-volume:/django/media
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  nginx:
    restart: always
    build: ./nginx
    volumes:
      # - ./frontend/dist:/web/dist
      - static-volume:/web/static
      - media-volume:/web/media
    ports:
      - 80:80
    depends_on:
      - django
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume: 
  media-volume: 
  database-volume: